[package]
name = "simple_test"
version = "0.1.0"
edition = "2018"


[dependencies]

integra8 = {path = "../../core/integra8", features = ["tokio-runtime"] }
integra8_tree_formatter = {path = "../../contrib/formatters/tree_formatter" }