[package]
name = "integra8_async_runtime"
version = "1.0.0"
edition = "2018"

[dependencies]
async-std = { version = "1.10.0",  optional = true}
tokio = { version = "1.12.0",  optional = true}

[features]
sync = []
async-std-runtime = ["async-std"]
tokio-runtime = ["tokio"]
