[package]
name = "integra8_formatters"
version = "1.0.0"
edition = "2018"


[dependencies]

structopt = "0.3"
term = "0.5"
integra8_context = {path = "../context"}
integra8_components = {path = "../components"}
integra8_results = {path = "../results"}
