[package]
name = "integra8_impl"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro-error = "1.0"
proc-macro2 = "1.0.32"

[features]
async-std-runtime = []
tokio-runtime = []